#!/bin/bash

# AWS Setup Commands for Portfolio Dashboard
# Run these commands one by one to setup AWS resources

echo "==================================="
echo "AWS Setup for Portfolio Dashboard"
echo "==================================="
echo ""

# Step 1: Configure AWS
echo "STEP 1: Configure AWS Credentials"
echo "=================================="
echo "Run: aws configure"
echo "You'll need:"
echo "  - AWS Access Key ID"
echo "  - AWS Secret Access Key"
echo "  - Default region: us-east-1"
echo ""
echo "aws configure"
echo ""

# Step 2: Create RDS Database (Optional - for storing history)
echo "STEP 2: Create PostgreSQL Database (Optional)"
echo "=============================================="
echo ""
echo "# Create security group for RDS"
echo "aws ec2 create-security-group \\"
echo "  --group-name portfolio-db-sg \\"
echo "  --description 'Security group for Portfolio DB'"
echo ""
echo "# Allow inbound on port 5432"
echo "aws ec2 authorize-security-group-ingress \\"
echo "  --group-name portfolio-db-sg \\"
echo "  --protocol tcp \\"
echo "  --port 5432 \\"
echo "  --cidr 0.0.0.0/0"
echo ""
echo "# Create RDS Database"
echo "aws rds create-db-instance \\"
echo "  --db-instance-identifier portfolio-db \\"
echo "  --db-instance-class db.t3.micro \\"
echo "  --engine postgres \\"
echo "  --allocated-storage 20 \\"
echo "  --master-username admin \\"
echo "  --master-user-password 'YourSecurePassword123!' \\"
echo "  --publicly-accessible \\"
echo "  --storage-encrypted"
echo ""

# Step 3: Store credentials in Secrets Manager
echo "STEP 3: Store Credentials in AWS Secrets Manager"
echo "=================================================="
echo ""
echo "aws secretsmanager create-secret \\"
echo "  --name portfolio-db-credentials \\"
echo "  --description 'Portfolio Database Credentials' \\"
echo "  --secret-string '{\"DB_HOST\":\"portfolio-db.xxxx.rds.amazonaws.com\",\"DB_NAME\":\"portfolio_db\",\"DB_USER\":\"admin\",\"DB_PASSWORD\":\"YourSecurePassword123!\"}'"
echo ""

# Step 4: Deploy to EB
echo "STEP 4: Deploy to Elastic Beanstalk"
echo "===================================="
echo ""
echo "# Install EB CLI (if needed)"
echo "pip install awsebcli"
echo ""
echo "# Initialize EB"
echo "eb init -p python-3.11 portfolio-dashboard"
echo ""
echo "# Create environment"
echo "eb create portfolio-env --instance-type t3.micro"
echo ""
echo "# Deploy"
echo "eb deploy"
echo ""
echo "# Open in browser"
echo "eb open"
echo ""

# Step 5: Setup CloudWatch Events for Lambda
echo "STEP 5: Schedule Lambda Updates (Every 1 Hour)"
echo "=============================================="
echo ""
echo "# Create Lambda role (if needed)"
echo "aws iam create-role \\"
echo "  --role-name lambda-portfolio-role \\"
echo "  --assume-role-policy-document file://trust-policy.json"
echo ""
echo "# Create CloudWatch rule"
echo "aws events put-rule \\"
echo "  --name portfolio-update-schedule \\"
echo "  --schedule-expression 'rate(1 hour)'"
echo ""
echo "# Add Lambda target"
echo "aws events put-targets \\"
echo "  --rule portfolio-update-schedule \\"
echo "  --targets 'Id=1,Arn=arn:aws:lambda:us-east-1:YOUR-ACCOUNT-ID:function:portfolio-updater'"
echo ""

# Step 6: Monitor
echo "STEP 6: Monitor Your Deployment"
echo "================================"
echo ""
echo "# View logs (stream live)"
echo "eb logs --all --stream"
echo ""
echo "# Check health"
echo "eb health"
echo ""
echo "# View environment info"
echo "eb open"
echo ""
echo "# Scale instances"
echo "eb scale 2"
echo ""

echo ""
echo "==================================="
echo "✅ Setup Complete!"
echo "==================================="
echo ""
echo "Your Portfolio Dashboard should now be:"
echo "✅ Running on Elastic Beanstalk"
echo "✅ Auto-updating via Lambda every hour"
echo "✅ Storing history in RDS"
echo "✅ Displaying in Streamlit UI"
echo ""
